### ISSUE TITLE
Convert Footage breaks on files with spaces in file names

### ISSUE THREAD

**Issue by C-Kenny** [tpraxl/convert-footage#5]
Just wanted to say thank you so much for this script. I got around the issue by changing replacing the spaces in the file names but wanted to express my gratification.

This script saved me so much time! Was able to use my clips in DaVinci Resolve 14 free edition running on Linux. 

Once again, thank you.

**Comment by tpraxl** [comment]
You're welcome. I appreciate your feedback very much and I will look into "spaces in filenames" as soon as I find the time. Other improvements are also on their way :)

**Comment by tpraxl** [comment]
Fixed in #8
