### ISSUE TITLE
Quality: 0 vs 1

### ISSUE THREAD

**Issue by LaKing** [tpraxl/convert-footage#9]
n is a number from 1-31, with 1 being highest quality/largest filesize
According to [ffmpg](https://trac.ffmpeg.org/wiki/Encode/MPEG-4)

**Comment by tpraxl** [comment]
Thanks for reporting this. @LaKing

I'll update the script and the documentation soon.

I'm curious: Did you encounter strange behavior or a difference in quality between the convert-footage quality 0 (default) and 1?
